/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef student_TYPES_H
#define student_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>




class Student;

typedef struct _Student__isset {
  _Student__isset() : sno(false), ssex(false), sage(false) {}
  bool sno :1;
  bool ssex :1;
  bool sage :1;
} _Student__isset;

class Student {
 public:

  static const char* ascii_fingerprint; // = "A3563C7FD103EEBC8BE054405C0D9AF8";
  static const uint8_t binary_fingerprint[16]; // = {0xA3,0x56,0x3C,0x7F,0xD1,0x03,0xEE,0xBC,0x8B,0xE0,0x54,0x40,0x5C,0x0D,0x9A,0xF8};

  Student(const Student&);
  Student& operator=(const Student&);
  Student() : sno(0), ssex(0), sage(0) {
  }

  virtual ~Student() throw();
  int32_t sno;
  bool ssex;
  int16_t sage;

  _Student__isset __isset;

  void __set_sno(const int32_t val);

  void __set_ssex(const bool val);

  void __set_sage(const int16_t val);

  bool operator == (const Student & rhs) const
  {
    if (!(sno == rhs.sno))
      return false;
    if (!(ssex == rhs.ssex))
      return false;
    if (!(sage == rhs.sage))
      return false;
    return true;
  }
  bool operator != (const Student &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const Student & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

  friend std::ostream& operator<<(std::ostream& out, const Student& obj);
};

void swap(Student &a, Student &b);



#endif
