/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "student_types.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>




Student::~Student() throw() {
}


void Student::__set_sno(const int32_t val) {
  this->sno = val;
}

void Student::__set_ssex(const bool val) {
  this->ssex = val;
}

void Student::__set_sage(const int16_t val) {
  this->sage = val;
}

const char* Student::ascii_fingerprint = "A3563C7FD103EEBC8BE054405C0D9AF8";
const uint8_t Student::binary_fingerprint[16] = {0xA3,0x56,0x3C,0x7F,0xD1,0x03,0xEE,0xBC,0x8B,0xE0,0x54,0x40,0x5C,0x0D,0x9A,0xF8};

uint32_t Student::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;


  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_I32) {
          xfer += iprot->readI32(this->sno);
          this->__isset.sno = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_BOOL) {
          xfer += iprot->readBool(this->ssex);
          this->__isset.ssex = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_I16) {
          xfer += iprot->readI16(this->sage);
          this->__isset.sage = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  return xfer;
}

uint32_t Student::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  oprot->incrementRecursionDepth();
  xfer += oprot->writeStructBegin("Student");

  xfer += oprot->writeFieldBegin("sno", ::apache::thrift::protocol::T_I32, 1);
  xfer += oprot->writeI32(this->sno);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("ssex", ::apache::thrift::protocol::T_BOOL, 2);
  xfer += oprot->writeBool(this->ssex);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("sage", ::apache::thrift::protocol::T_I16, 3);
  xfer += oprot->writeI16(this->sage);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  oprot->decrementRecursionDepth();
  return xfer;
}

void swap(Student &a, Student &b) {
  using ::std::swap;
  swap(a.sno, b.sno);
  swap(a.ssex, b.ssex);
  swap(a.sage, b.sage);
  swap(a.__isset, b.__isset);
}

Student::Student(const Student& other0) {
  sno = other0.sno;
  ssex = other0.ssex;
  sage = other0.sage;
  __isset = other0.__isset;
}
Student& Student::operator=(const Student& other1) {
  sno = other1.sno;
  ssex = other1.ssex;
  sage = other1.sage;
  __isset = other1.__isset;
  return *this;
}
std::ostream& operator<<(std::ostream& out, const Student& obj) {
  using apache::thrift::to_string;
  out << "Student(";
  out << "sno=" << to_string(obj.sno);
  out << ", " << "ssex=" << to_string(obj.ssex);
  out << ", " << "sage=" << to_string(obj.sage);
  out << ")";
  return out;
}


